FROM mcr.microsoft.com/devcontainers/javascript-node:0-22

# [Optional] If your app requires additional system packages, install them here
# RUN apt-get update && apt-get install -y --no-install-recommends <packages>

# Default user in the official images is 'vscode' so no additional user setup is required.
